import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/** @type {import('next').NextConfig} */
const nextConfig = {
  // @barter/db and @barter/ui ship raw TypeScript — Next must compile them into
  // the bundle instead of copying uncompiled .ts into the function (which would
  // throw at runtime). Same lesson as apps/web (Phase 2b/2c).
  transpilePackages: ["@barter/db", "@barter/ui"],
  // Trace from the monorepo root so the hoisted Prisma query-engine binary
  // (generated by @barter/db into ../../node_modules) is bundled into the
  // admin serverless functions.
  outputFileTracingRoot: path.join(__dirname, "../../"),
  eslint: {
    ignoreDuringBuilds: true,
  },
  typescript: {
    ignoreBuildErrors: true,
  },
  images: {
    unoptimized: true,
  },
};

export default nextConfig;
