// @barter/types — shared cross-app TypeScript types.
//
// Intentionally empty for now (T038). Populate with cross-cutting, non-Prisma
// types as they are identified during the admin-app work (US1): request/response
// DTOs shared between apps/web and apps/admin, and any enums not generated by
// Prisma (those live in @barter/db). Prisma model types must NOT be duplicated
// here — import them from @barter/db.

export {};
